[profile.default]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read", path = "./images" },
]
